import {
  orgData, teamData, workOrders, portfolio, ownerColors, countUnowned,
} from './state.js';
import { getOpsProfile, getCompanyName, _showActionToast } from './storage.js';
import { escapeHtml, _slugify } from './utils.js';

// Maintainer note:
// This module powers the top-of-dashboard Launch Plan and "Start Here" next
// step buttons. It reads live state from state.js, profile data from storage.js,
// and exposes handlers through app.js -> window for inline onclicks. If you
// rename exported functions here, update app.js Object.assign(window, ...) and
// any onclick strings generated by renderLaunchPlan().

const LAUNCH_CHECKLIST_KEY = 'pm-ops-launch-checklist-v1';

const PROFILE_LABELS = {
  small: 'Under 100 doors',
  mid: '100-500 doors',
  large: '500+ doors',
  stability: 'Stabilize ownership',
  maintenance: 'Tighten maintenance flow',
  growth: 'Scale team capacity',
  compliance: 'Reduce compliance risk',
};

const FOCUS_BLUEPRINTS = {
  // Department ids must exist in config.json. Missing ids are filtered out at
  // render time, but that makes the recommended blueprint feel incomplete.
  stability: {
    title: 'Ownership Stabilization',
    summary: 'Get every recurring responsibility named, backed up, and visible before the week gets noisy.',
    departments: ['tenant-comms', 'maintenance', 'delinquency', 'owner-relations'],
  },
  maintenance: {
    title: 'Maintenance Command Center',
    summary: 'Stand up intake, vendor routing, emergency escalation, and closeout discipline from day one.',
    departments: ['maintenance', 'vendors', 'unit-turns', 'tenant-comms'],
  },
  growth: {
    title: 'Scalable Team Capacity',
    summary: 'Separate daily operating work from growth work so new doors do not bury the team.',
    departments: ['leasing', 'applications', 'move-ins', 'accounting'],
  },
  compliance: {
    title: 'Compliance-Safe Operations',
    summary: 'Make the highest-risk duties explicit, documented, and reviewed on a reliable cadence.',
    departments: ['compliance', 'delinquency', 'accounting', 'reporting'],
  },
};

const BASE_CHECKLIST = [
  {
    id: 'portfolio',
    label: 'Add the first managed property and vendor',
    detail: 'Record at least one property plus one reliable vendor so the operating map has real-world context.',
    metric: () => portfolio.properties.length > 0 && portfolio.tenants.length > 0 && portfolio.vendors.length > 0,
  },
  {
    id: 'owners',
    label: 'Assign every red UNOWNED responsibility',
    detail: 'Start with daily tenant, maintenance, rent, and owner communication work.',
    metric: () => countUnowned() === 0,
  },
  {
    id: 'critical-coverage',
    label: 'Cover the seven critical PM responsibility lanes',
    detail: 'Confirm leasing, rent collection, inspections, maintenance, compliance, renewals, and emergencies have named owners.',
    metric: () => getCriticalCoverageAreas().every(area => area.coveragePct >= 70),
  },
  {
    id: 'maintenance',
    label: 'Define maintenance intake and escalation',
    detail: 'Name who monitors the queue, who dispatches vendors, and who handles after-hours emergencies.',
    metric: () => hasAssignedDepartment('maintenance') && hasAnyWorkOrderSignal(),
  },
  {
    id: 'rent',
    label: 'Lock the rent collection routine',
    detail: 'Confirm who reviews delinquencies, sends notices, answers ledger questions, and escalates legal handoff.',
    metric: () => hasAssignedDepartment('delinquency') && hasAssignedDepartment('accounting'),
  },
  {
    id: 'vendors',
    label: 'Create the starter vendor bench',
    detail: 'Add at least one work order with a vendor or document the preferred vendor owner.',
    metric: () => workOrders.some(w => (w.vendor || '').trim()),
  },
  {
    id: 'owner-reporting',
    label: 'Set owner reporting expectations',
    detail: 'Pick the owner communication lead and define the weekly update rhythm.',
    metric: () => hasAssignedDepartment('owner-relations'),
  },
];

const FOCUS_CHECKLIST = {
  maintenance: [
    {
      id: 'maintenance-aging',
      label: 'Review open repair aging every morning',
      detail: 'Use Work Orders to keep submitted and in-progress jobs from going stale.',
      metric: () => workOrders.some(w => w.status !== 'completed'),
    },
  ],
  growth: [
    {
      id: 'leasing-capacity',
      label: 'Separate leasing growth work from operations work',
      detail: 'Make sure showings, applications, and move-ins have named owners before adding doors.',
      metric: () => hasAssignedDepartment('leasing') && hasAssignedDepartment('applications') && hasAssignedDepartment('move-ins'),
    },
  ],
  compliance: [
    {
      id: 'inspection-cadence',
      label: 'Document inspection and compliance cadence',
      detail: 'Assign inspections, notices, and recordkeeping before exceptions start piling up.',
      metric: () => hasAssignedDepartment('unit-turns') && hasAssignedDepartment('compliance'),
    },
  ],
  stability: [
    {
      id: 'backup-coverage',
      label: 'Check backup coverage for overloaded roles',
      detail: 'Use Team Manager to rebalance any person carrying a large share of the operating map.',
      metric: () => getOverloadedOwners().length === 0,
    },
  ],
};

const CRITICAL_COVERAGE_AREAS = [
  {
    id: 'leasing',
    label: 'Leasing',
    detail: 'Listings, showings, applications, and move-in handoff.',
    departments: ['leasing', 'applications', 'move-ins'],
  },
  {
    id: 'rent',
    label: 'Rent Collection',
    detail: 'Delinquencies, ledgers, notices, and payment follow-up.',
    departments: ['delinquency', 'accounting'],
  },
  {
    id: 'inspections',
    label: 'Inspections',
    detail: 'Move-ins, move-outs, turns, field visits, and condition reports.',
    departments: ['move-ins', 'move-outs', 'unit-turns', 'field-services'],
  },
  {
    id: 'maintenance',
    label: 'Maintenance',
    detail: 'Intake, triage, vendors, emergency dispatch, and closeout.',
    departments: ['maintenance', 'vendors'],
  },
  {
    id: 'compliance',
    label: 'Compliance',
    detail: 'Fair housing, notices, insurance, records, and risk controls.',
    departments: ['compliance', 'reporting'],
  },
  {
    id: 'renewals',
    label: 'Renewals',
    detail: 'Rent increases, lease questions, move-outs, and owner alignment.',
    departments: ['tenant-comms', 'owner-relations', 'leasing'],
  },
  {
    id: 'emergencies',
    label: 'Emergencies',
    detail: 'After-hours repair response, access, vendors, and tenant updates.',
    departments: ['maintenance', 'vendors', 'field-services', 'tenant-comms'],
  },
];

export function renderLaunchPlan() {
  // Called by app init, ui.updateStats(), onboarding submit, checklist changes,
  // and guided action handlers. Keep this render idempotent and derived from
  // current state; do not mutate orgData/teamData/workOrders here.
  const container = document.getElementById('launch-plan');
  if (!container || !orgData) return;

  const profile = getOpsProfile();
  const focus = profile.focus || 'stability';
  const blueprint = FOCUS_BLUEPRINTS[focus] || FOCUS_BLUEPRINTS.stability;
  const checklist = getLaunchChecklist(focus);
  const saved = readChecklistState();
  const completeCount = checklist.filter(item => saved[item.id] || item.metric()).length;
  const gaps = getLaunchGaps();
  const nextAction = getNextAction();
  const readiness = getReadinessScore(checklist, saved);
  const snapshot = getOperationsSnapshot();
  const commandModules = getCommandModules(snapshot);
  const riskQueue = getRiskQueue(snapshot);
  const coverageAreas = getCriticalCoverageAreas();
  const blueprintDepts = blueprint.departments
    .map(id => orgData.departments.find(dept => dept.id === id))
    .filter(Boolean);

  container.innerHTML = `
    <div class="launch-dashboard-header">
      <div>
        <div class="launch-kicker">Beginner PM Command Center</div>
        <h3>${escapeHtml(getCompanyName())} operating snapshot</h3>
        <p>One place to set ownership, catch maintenance risk, build the team routine, and export the handbook before the company needs heavyweight software.</p>
      </div>
      <div class="launch-readiness-card" aria-label="${readiness.score} percent launch readiness">
        <strong>${readiness.score}%</strong>
        <span>${escapeHtml(readiness.label)}</span>
      </div>
    </div>
    <div class="launch-metrics-grid" aria-label="Launch readiness metrics">
      ${renderMetricCard('Portfolio', String(snapshot.propertyCount), `${snapshot.unitCount} units / ${snapshot.tenantCount} tenants / ${snapshot.vendorCount} vendors`, snapshot.propertyCount && snapshot.tenantCount && snapshot.vendorCount ? 'good' : 'warn')}
      ${renderMetricCard('Owned tasks', `${snapshot.assignedTasks}/${snapshot.totalTasks}`, `${snapshot.unownedTasks} unowned`, snapshot.unownedTasks ? 'warn' : 'good')}
      ${renderMetricCard('Team roster', String(snapshot.employeeCount), snapshot.isStarterTeam ? 'sample roster' : 'real people', snapshot.isStarterTeam ? 'warn' : 'good')}
      ${renderMetricCard('Open repairs', String(snapshot.openWorkOrders), `${snapshot.unassignedWorkOrders} unassigned`, snapshot.unassignedWorkOrders ? 'warn' : 'good')}
      ${renderMetricCard('Blocked work', String(snapshot.blockedTasks), `${snapshot.overdueTasks} overdue`, snapshot.blockedTasks || snapshot.overdueTasks ? 'danger' : 'good')}
    </div>
    <div class="launch-start">
      <div>
        <div class="launch-kicker">Start Here</div>
        <h3>${escapeHtml(nextAction.title)}</h3>
        <p>${escapeHtml(nextAction.detail)}</p>
      </div>
      <button class="btn btn-primary launch-primary-action" onclick="${nextAction.onclick}">
        ${escapeHtml(nextAction.button)}
      </button>
    </div>
    <div class="launch-command-grid" aria-label="Beginner property manager modules">
      ${commandModules.map(renderCommandModule).join('')}
    </div>
    <div class="launch-coverage-panel" aria-label="Critical responsibility coverage">
      <div class="launch-coverage-head">
        <div>
          <div class="launch-kicker">Task Ownership Map</div>
          <h3>Critical PM coverage</h3>
          <p>These are the seven responsibility lanes a beginner property manager needs named before the work gets noisy.</p>
        </div>
        <div class="launch-coverage-score">
          <strong>${coverageAreas.filter(area => area.coveragePct === 100).length}/${coverageAreas.length}</strong>
          <span>fully covered</span>
        </div>
      </div>
      <div class="launch-coverage-grid">
        ${coverageAreas.map(renderCoverageArea).join('')}
      </div>
    </div>
    <div class="launch-risk-panel">
      <div>
        <div class="launch-kicker">Risk Queue</div>
        <h3>What needs attention before this can run cleanly?</h3>
      </div>
      <div class="launch-risk-list">
        ${riskQueue.length
          ? riskQueue.map(renderRiskItem).join('')
          : '<div class="launch-risk-empty">No major launch risks detected. Keep adding real properties, vendors, dates, and SOP detail as work comes in.</div>'
        }
      </div>
    </div>
    <div class="launch-plan-header">
      <div>
        <div class="launch-kicker">Launch Plan</div>
        <h3>${escapeHtml(blueprint.title)}</h3>
        <p>${escapeHtml(blueprint.summary)}</p>
      </div>
      <div class="launch-score" aria-label="${completeCount} of ${checklist.length} launch steps complete">
        <strong>${completeCount}/${checklist.length}</strong>
        <span>ready steps</span>
      </div>
    </div>
    <div class="launch-plan-grid">
      <div class="launch-panel">
        <div class="launch-panel-title">Recommended Blueprint</div>
        <div class="launch-profile-line">
          ${escapeHtml(PROFILE_LABELS[profile.portfolioSize] || PROFILE_LABELS.mid)} / ${escapeHtml(PROFILE_LABELS[focus] || PROFILE_LABELS.stability)}
        </div>
        <div class="launch-dept-list">
          ${blueprintDepts.map(dept => `
            <button class="launch-dept-pill" style="--dept-color:${dept.color}" onclick="focusLaunchDepartment('${dept.id}')">
              ${escapeHtml(dept.name)}
            </button>
          `).join('')}
        </div>
      </div>
      <div class="launch-panel">
        <div class="launch-panel-title">First-Week Checklist</div>
        <div class="launch-checklist">
          ${checklist.map(item => renderChecklistItem(item, saved[item.id])).join('')}
        </div>
      </div>
      <div class="launch-panel launch-gap-panel">
        <div class="launch-panel-title">Setup Gaps</div>
        ${gaps.length
          ? `<div class="launch-gap-list">${gaps.map(gap => `
              <div class="launch-gap">
                <strong>${escapeHtml(gap.title)}</strong>
                <span>${escapeHtml(gap.detail)}</span>
              </div>
            `).join('')}</div>`
          : '<p class="launch-empty">Core launch signals look good. Keep tightening owners, dates, and playbooks as the company grows.</p>'
        }
      </div>
    </div>
    <div class="launch-actions">
      <button class="btn btn-secondary" onclick="downloadLaunchPlan()">Download Launch Plan</button>
      <button class="btn btn-secondary" onclick="resetLaunchChecklist()">Reset Checklist</button>
    </div>
  `;
}

export function toggleLaunchChecklistItem(id, checked) {
  const state = readChecklistState();
  state[id] = Boolean(checked);
  writeChecklistState(state);
  renderLaunchPlan();
}

export function resetLaunchChecklist() {
  try { localStorage.removeItem(LAUNCH_CHECKLIST_KEY); } catch (_) {}
  renderLaunchPlan();
}

export function startTeamSetup() {
  // Used by the generated Start Here button. app.js must expose this on window.
  switchToView('team', 'team-tab');
  document.getElementById('new-emp-name')?.focus();
}

export function showUnownedTasks() {
  // Depends on tracking.js exposing applyFilter on window through app.js.
  switchToView('tracking', document.querySelector('.nav-tab'));
  const ownerFilter = document.getElementById('owner-filter');
  if (ownerFilter) ownerFilter.value = 'UNOWNED';
  if (window.applyFilter) window.applyFilter();
  document.getElementById('departments')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
}

export function startWorkOrderSetup() {
  // Depends on workorders.js exposing showNewWorkOrderModal on window via app.js.
  switchToView('workorders', 'wo-tab');
  setTimeout(() => {
    if (window.showNewWorkOrderModal) window.showNewWorkOrderModal();
  }, 100);
}

export function downloadLaunchHandbook() {
  // Depends on handbook.js exposing downloadOperationsHandbook on window via app.js.
  if (window.downloadOperationsHandbook) window.downloadOperationsHandbook();
}

export function focusLaunchDepartment(deptId) {
  const deptEl = document.querySelector(`.department[data-id="${deptId}"]`);
  if (!deptEl) return;
  deptEl.style.display = '';
  deptEl.classList.add('expanded');
  deptEl.scrollIntoView({ behavior: 'smooth', block: 'start' });
  deptEl.classList.add('launch-highlight');
  setTimeout(() => deptEl.classList.remove('launch-highlight'), 1600);
}

export function downloadLaunchPlan() {
  const profile = getOpsProfile();
  const focus = profile.focus || 'stability';
  const blueprint = FOCUS_BLUEPRINTS[focus] || FOCUS_BLUEPRINTS.stability;
  const saved = readChecklistState();
  const checklist = getLaunchChecklist(focus);
  const gaps = getLaunchGaps();
  const coverage = getCriticalCoverageAreas();
  const company = getCompanyName();
  const lines = [
    `# ${company} Launch Plan`,
    '',
    `Blueprint: ${blueprint.title}`,
    `Portfolio: ${PROFILE_LABELS[profile.portfolioSize] || PROFILE_LABELS.mid}`,
    `Focus: ${PROFILE_LABELS[focus] || PROFILE_LABELS.stability}`,
    '',
    '## First-Week Checklist',
    ...checklist.map(item => `- [${saved[item.id] || item.metric() ? 'x' : ' '}] ${item.label} - ${item.detail}`),
    '',
    '## Critical Coverage',
    ...coverage.map(area => `- ${area.label}: ${area.coveragePct}% covered (${area.unownedCount} unowned / ${area.taskCount} tasks). Owners: ${area.primaryOwners}`),
    '',
    '## Setup Gaps',
    ...(gaps.length ? gaps.map(gap => `- ${gap.title}: ${gap.detail}`) : ['- No major setup gaps detected.']),
  ];

  const blob = new Blob([lines.join('\n')], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${_slugify(company)}-launch-plan.md`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
  _showActionToast('Launch plan downloaded', 'save-toast--success');
}

function renderChecklistItem(item, manuallyChecked) {
  const complete = manuallyChecked || item.metric();
  return `
    <label class="launch-check-item ${complete ? 'is-complete' : ''}">
      <input type="checkbox" ${complete ? 'checked' : ''} onchange="toggleLaunchChecklistItem('${item.id}', this.checked)">
      <span>
        <strong>${escapeHtml(item.label)}</strong>
        <small>${escapeHtml(item.detail)}</small>
      </span>
    </label>
  `;
}

function renderMetricCard(label, value, detail, tone) {
  return `
    <div class="launch-metric-card launch-metric-card--${tone}">
      <span>${escapeHtml(label)}</span>
      <strong>${escapeHtml(value)}</strong>
      <small>${escapeHtml(detail)}</small>
    </div>
  `;
}

function renderCommandModule(module) {
  return `
    <div class="launch-command-card launch-command-card--${module.tone}">
      <div class="launch-command-top">
        <span class="launch-command-icon">${module.icon}</span>
        <span class="launch-command-status">${escapeHtml(module.status)}</span>
      </div>
      <strong>${escapeHtml(module.title)}</strong>
      <p>${escapeHtml(module.detail)}</p>
      <button class="btn btn-secondary launch-command-btn" onclick="${module.onclick}">
        ${escapeHtml(module.button)}
      </button>
    </div>
  `;
}

function renderRiskItem(risk) {
  return `
    <button class="launch-risk-item launch-risk-item--${risk.tone}" onclick="${risk.onclick}">
      <span>${escapeHtml(risk.label)}</span>
      <strong>${escapeHtml(risk.title)}</strong>
      <small>${escapeHtml(risk.detail)}</small>
    </button>
  `;
}

function renderCoverageArea(area) {
  const tone = area.coveragePct === 100 ? 'good' : area.coveragePct >= 70 ? 'warn' : 'danger';
  return `
    <button class="launch-coverage-card launch-coverage-card--${tone}" onclick="focusCoverageArea('${area.id}')">
      <span>${escapeHtml(area.label)}</span>
      <strong>${area.coveragePct}%</strong>
      <small>${area.unownedCount} unowned / ${area.taskCount} tasks</small>
      <em>${escapeHtml(area.primaryOwners)}</em>
    </button>
  `;
}

function getLaunchChecklist(focus) {
  return [...BASE_CHECKLIST, ...(FOCUS_CHECKLIST[focus] || [])];
}

function getReadinessScore(checklist, saved) {
  const snapshot = getOperationsSnapshot();
  const checklistComplete = checklist.filter(item => saved[item.id] || item.metric()).length / Math.max(checklist.length, 1);
  const ownershipScore = snapshot.totalTasks ? snapshot.assignedTasks / snapshot.totalTasks : 0;
  const teamScore = snapshot.employeeCount && !snapshot.isStarterTeam ? 1 : 0.35;
  const portfolioScore = (snapshot.propertyCount ? 0.42 : 0) + (snapshot.tenantCount ? 0.28 : 0) + (snapshot.vendorCount ? 0.3 : 0);
  const maintenanceScore = snapshot.workOrderCount
    ? Math.max(0.25, 1 - (snapshot.unassignedWorkOrders / Math.max(snapshot.openWorkOrders, 1)))
    : 0.25;
  const riskPenalty = Math.min(0.25, ((snapshot.blockedTasks + snapshot.overdueTasks) / Math.max(snapshot.totalTasks, 1)) * 2);
  const score = Math.max(0, Math.min(100, Math.round(
    ((ownershipScore * 0.3) + (teamScore * 0.2) + (portfolioScore * 0.16) + (maintenanceScore * 0.16) + (checklistComplete * 0.18) - riskPenalty) * 100
  )));

  let label = 'Needs setup';
  if (score >= 85) label = 'Launch ready';
  else if (score >= 65) label = 'Operational';
  else if (score >= 40) label = 'Getting organized';

  return { score, label };
}

function getOperationsSnapshot() {
  const totalTasks = orgData.departments.reduce((sum, dept) => sum + dept.tasks.length, 0);
  const unownedTasks = countUnowned();
  const assignedTasks = totalTasks - unownedTasks;
  const blockedTasks = orgData.departments.reduce(
    (sum, dept) => sum + dept.tasks.filter(task => task.status === 'blocked').length,
    0
  );
  const todayISO = new Date().toISOString().slice(0, 10);
  const overdueTasks = orgData.departments.reduce(
    (sum, dept) => sum + dept.tasks.filter(task => task.dueDate && task.dueDate < todayISO && task.status !== 'done').length,
    0
  );
  const openWorkOrders = workOrders.filter(w => w.status !== 'completed').length;
  const unassignedWorkOrders = workOrders.filter(w => w.assignee === 'UNASSIGNED' && w.status !== 'completed').length;

  return {
    totalTasks,
    assignedTasks,
    unownedTasks,
    blockedTasks,
    overdueTasks,
    workOrderCount: workOrders.length,
    openWorkOrders,
    unassignedWorkOrders,
    propertyCount: portfolio.properties.length,
    unitCount: portfolio.properties.reduce((sum, property) => sum + Number(property.units || 0), 0),
    tenantCount: portfolio.tenants.length,
    vendorCount: portfolio.vendors.length,
    employeeCount: teamData.employees.length,
    isStarterTeam: isStarterTeam(),
  };
}

function getCriticalCoverageAreas() {
  return CRITICAL_COVERAGE_AREAS.map(area => {
    const depts = area.departments
      .map(id => orgData.departments.find(dept => dept.id === id))
      .filter(Boolean);
    const tasks = depts.flatMap(dept => dept.tasks);
    const unownedCount = tasks.filter(task => task.owner === 'UNOWNED').length;
    const ownerCounts = new Map();
    tasks.forEach(task => {
      if (task.owner !== 'UNOWNED') ownerCounts.set(task.owner, (ownerCounts.get(task.owner) || 0) + 1);
    });
    const primaryOwners = [...ownerCounts.entries()]
      .sort((a, b) => b[1] - a[1])
      .slice(0, 3)
      .map(([name]) => name)
      .join(', ') || 'No named owner';

    return {
      ...area,
      taskCount: tasks.length,
      unownedCount,
      primaryOwners,
      coveragePct: tasks.length ? Math.round(((tasks.length - unownedCount) / tasks.length) * 100) : 0,
    };
  });
}

function getCommandModules(snapshot) {
  return [
    {
      icon: '01',
      title: 'Portfolio Basics',
      status: snapshot.propertyCount ? `${snapshot.propertyCount} properties` : 'missing',
      tone: snapshot.propertyCount && snapshot.tenantCount && snapshot.vendorCount ? 'good' : 'warn',
      detail: 'Capture properties, unit counts, owner/client names, tenant roster, and starter vendor bench before daily work starts moving.',
      button: 'Open Portfolio',
      onclick: "switchView('portfolio', document.getElementById('portfolio-tab'))",
    },
    {
      icon: '02',
      title: 'Ownership Map',
      status: snapshot.unownedTasks ? `${snapshot.unownedTasks} gaps` : 'ready',
      tone: snapshot.unownedTasks ? 'warn' : 'good',
      detail: 'Name who owns every recurring operating responsibility across leasing, maintenance, accounting, compliance, and owner updates.',
      button: snapshot.unownedTasks ? 'Close Gaps' : 'Review Map',
      onclick: snapshot.unownedTasks ? 'showUnownedTasks()' : "switchView('map', document.querySelector('[onclick*=map]'))",
    },
    {
      icon: '03',
      title: 'Team Operating Model',
      status: snapshot.isStarterTeam ? 'sample team' : `${snapshot.employeeCount} people`,
      tone: snapshot.isStarterTeam ? 'warn' : 'good',
      detail: 'Replace sample roles with real people, set department affinities, and spot overload before work becomes invisible.',
      button: 'Open Team',
      onclick: 'startTeamSetup()',
    },
    {
      icon: '04',
      title: 'Maintenance Flow',
      status: snapshot.workOrderCount ? `${snapshot.openWorkOrders} open` : 'not tested',
      tone: snapshot.unassignedWorkOrders || !snapshot.workOrderCount ? 'warn' : 'good',
      detail: 'Validate intake, dispatch, vendor, cost, due date, and closeout with at least one starter work order.',
      button: snapshot.workOrderCount ? 'Open Board' : 'Create First WO',
      onclick: snapshot.workOrderCount ? "switchView('workorders', document.getElementById('wo-tab'))" : 'startWorkOrderSetup()',
    },
    {
      icon: '05',
      title: 'SOP Handbook',
      status: snapshot.unownedTasks ? 'draft only' : 'exportable',
      tone: snapshot.unownedTasks ? 'neutral' : 'good',
      detail: 'Turn the live map into a Markdown starter handbook so new managers have a source of truth from day one.',
      button: 'Download SOP',
      onclick: 'downloadLaunchHandbook()',
    },
  ];
}

function getRiskQueue(snapshot) {
  const risks = [];
  const weakCoverage = getCriticalCoverageAreas().filter(area => area.coveragePct < 70);
  if (weakCoverage.length) {
    risks.push({
      label: 'Ownership Map',
      title: `${weakCoverage.length} critical coverage lane${weakCoverage.length === 1 ? '' : 's'} under 70%`,
      detail: `${weakCoverage.map(area => area.label).slice(0, 3).join(', ')} need clearer ownership.`,
      tone: 'danger',
      onclick: `focusCoverageArea('${weakCoverage[0].id}')`,
    });
  }
  if (!snapshot.propertyCount) {
    risks.push({
      label: 'Portfolio',
      title: 'No managed properties are recorded',
      detail: 'Add at least one property with units and owner/client context.',
      tone: 'warn',
      onclick: "switchView('portfolio', document.getElementById('portfolio-tab'))",
    });
  }
  if (!snapshot.tenantCount) {
    risks.push({
      label: 'Tenants',
      title: 'No tenant roster exists yet',
      detail: 'Add at least one tenant so maintenance and communication have unit-level context.',
      tone: 'warn',
      onclick: "switchView('portfolio', document.getElementById('portfolio-tab'))",
    });
  }
  if (!snapshot.vendorCount) {
    risks.push({
      label: 'Vendors',
      title: 'No starter vendor bench exists',
      detail: 'Add at least one vendor before the first urgent repair hits.',
      tone: 'warn',
      onclick: "switchView('portfolio', document.getElementById('portfolio-tab'))",
    });
  }
  if (snapshot.isStarterTeam) {
    risks.push({
      label: 'Team',
      title: 'Sample people are still assigned',
      detail: 'Replace starter owners with your real team before trusting the map.',
      tone: 'warn',
      onclick: 'startTeamSetup()',
    });
  }
  if (snapshot.unownedTasks > 0) {
    risks.push({
      label: 'Ownership',
      title: `${snapshot.unownedTasks} responsibilities have no owner`,
      detail: 'These are the highest-value gaps to close for a beginner PM company.',
      tone: 'danger',
      onclick: 'showUnownedTasks()',
    });
  }
  if (!snapshot.workOrderCount) {
    risks.push({
      label: 'Maintenance',
      title: 'Maintenance workflow has not been tested',
      detail: 'Create one realistic work order to prove intake, assignment, vendor, cost, and closeout.',
      tone: 'warn',
      onclick: 'startWorkOrderSetup()',
    });
  } else if (snapshot.unassignedWorkOrders > 0) {
    risks.push({
      label: 'Maintenance',
      title: `${snapshot.unassignedWorkOrders} open work orders are unassigned`,
      detail: 'Every repair needs a named accountable person.',
      tone: 'danger',
      onclick: "switchView('workorders', document.getElementById('wo-tab'))",
    });
  }
  if (snapshot.blockedTasks || snapshot.overdueTasks) {
    risks.push({
      label: 'Execution',
      title: `${snapshot.blockedTasks} blocked / ${snapshot.overdueTasks} overdue tasks`,
      detail: 'Review blocked or late responsibilities before the operating map becomes stale.',
      tone: 'danger',
      onclick: "switchView('tracking', document.querySelector('.nav-tab'))",
    });
  }
  return risks.slice(0, 4);
}

function getNextAction() {
  // Beginner guidance engine. Order is intentional:
  // define portfolio -> personalize sample roster -> close UNOWNED task gaps ->
  // create maintenance workflow -> export handbook. Changing this order changes first-run UX.
  const unowned = countUnowned();
  const openUnassignedWorkOrders = workOrders.filter(w => w.assignee === 'UNASSIGNED' && w.status !== 'completed').length;

  if (!portfolio.properties.length || !portfolio.tenants.length || !portfolio.vendors.length) {
    return {
      title: 'Add your first property, tenant, and vendor',
      detail: 'Start by recording what you manage, who lives there, and who you can call for repairs. This makes the rest of the operating map feel real.',
      button: 'Open Portfolio',
      onclick: "switchView('portfolio', document.getElementById('portfolio-tab'))",
    };
  }

  if (!teamData.employees.length || isStarterTeam()) {
    return {
      title: 'Add your real team first',
      detail: 'The starter map has sample owners. Replace them with your people so every responsibility can point to a real person.',
      button: 'Open Team Manager',
      onclick: 'startTeamSetup()',
    };
  }

  if (unowned > 0) {
    return {
      title: `Assign ${unowned} unowned responsibilities`,
      detail: 'Red UNOWNED items are the highest-priority setup gaps. Click each owner badge or use Auto-Assign after your team affinities look right.',
      button: 'Show Unowned Tasks',
      onclick: 'showUnownedTasks()',
    };
  }

  if (!workOrders.length || openUnassignedWorkOrders > 0) {
    return {
      title: 'Create a starter work order',
      detail: 'Use one sample repair to confirm intake, assignment, vendor, cost, target date, and closeout before real maintenance work arrives.',
      button: 'Create Work Order',
      onclick: 'startWorkOrderSetup()',
    };
  }

  return {
    title: 'Download your operations handbook',
    detail: 'Your core setup signals look good. Export the handbook so the team has a simple SOP starter pack to review and improve.',
    button: 'Download Handbook',
    onclick: 'downloadLaunchHandbook()',
  };
}

function switchToView(view, tabRef) {
  const tabEl = typeof tabRef === 'string' ? document.getElementById(tabRef) : tabRef;
  if (window.switchView && tabEl) window.switchView(view, tabEl);
}

export function focusCoverageArea(areaId) {
  const area = CRITICAL_COVERAGE_AREAS.find(item => item.id === areaId);
  if (!area) return;
  switchToView('tracking', document.querySelector('.nav-tab'));
  area.departments.forEach(deptId => {
    const deptEl = document.querySelector(`.department[data-id="${deptId}"]`);
    if (!deptEl) return;
    deptEl.style.display = '';
    deptEl.classList.add('expanded', 'launch-highlight');
    setTimeout(() => deptEl.classList.remove('launch-highlight'), 1600);
  });
  const firstDept = area.departments
    .map(deptId => document.querySelector(`.department[data-id="${deptId}"]`))
    .find(Boolean);
  firstDept?.scrollIntoView({ behavior: 'smooth', block: 'start' });
}

function isStarterTeam() {
  // The default team is seeded from config.json ownerColors. If the current
  // roster still exactly matches those sample names, guide users to replace it
  // before trusting assignments.
  if (!ownerColors || !teamData.employees.length) return false;
  const starterNames = Object.keys(ownerColors)
    .filter(name => name !== 'UNOWNED')
    .sort();
  const currentNames = teamData.employees.map(emp => emp.name).sort();
  if (starterNames.length !== currentNames.length) return false;
  return starterNames.every((name, idx) => currentNames[idx] === name);
}

function readChecklistState() {
  try {
    return JSON.parse(localStorage.getItem(LAUNCH_CHECKLIST_KEY)) || {};
  } catch (_) {
    return {};
  }
}

function writeChecklistState(state) {
  try { localStorage.setItem(LAUNCH_CHECKLIST_KEY, JSON.stringify(state)); } catch (_) {}
}

function hasAssignedDepartment(deptId) {
  const dept = orgData.departments.find(d => d.id === deptId);
  return Boolean(dept && dept.tasks.some(task => task.owner !== 'UNOWNED'));
}

function hasAnyWorkOrderSignal() {
  return workOrders.length > 0 || hasAssignedDepartment('maintenance');
}

function getOverloadedOwners() {
  if (!teamData.employees.length || !orgData) return [];
  const counts = new Map(teamData.employees.map(emp => [emp.name, 0]));
  orgData.departments.forEach(dept => {
    dept.tasks.forEach(task => {
      if (counts.has(task.owner)) counts.set(task.owner, counts.get(task.owner) + 1);
    });
  });
  const totalAssigned = [...counts.values()].reduce((sum, count) => sum + count, 0);
  const average = totalAssigned / Math.max(counts.size, 1);
  return [...counts.entries()]
    .filter(([, count]) => count > Math.max(35, average * 1.8))
    .map(([name]) => name);
}

function getLaunchGaps() {
  const gaps = [];
  const unowned = countUnowned();
  const overloaded = getOverloadedOwners();
  const unassignedWorkOrders = workOrders.filter(w => w.assignee === 'UNASSIGNED' && w.status !== 'completed').length;

  if (unowned > 0) {
    gaps.push({
      title: `${unowned} unowned responsibilities`,
      detail: 'Assign these before using the map as the operating source of truth.',
    });
  }
  if (!teamData.employees.length) {
    gaps.push({
      title: 'No team roster',
      detail: 'Add the first employees in Team Manager so responsibilities have real owners.',
    });
  }
  if (unassignedWorkOrders > 0) {
    gaps.push({
      title: `${unassignedWorkOrders} unassigned open work order${unassignedWorkOrders === 1 ? '' : 's'}`,
      detail: 'Assign each open job so maintenance does not become invisible work.',
    });
  }
  if (!workOrders.length) {
    gaps.push({
      title: 'No sample maintenance workflow',
      detail: 'Create one starter work order to validate intake, assignment, vendor, and closeout steps.',
    });
  }
  if (overloaded.length > 0) {
    gaps.push({
      title: 'Potential role overload',
      detail: `${overloaded.slice(0, 3).join(', ')} may need backup coverage or reassignment.`,
    });
  }

  return gaps.slice(0, 5);
}
